# Generated by Django 3.0.5 on 2020-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_prod_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
